/* AUTO-GENERATED FILE. DO NOT MODIFY.
 * This class was automatically generated by the
 * static binding generator from the resources it found.
 * Please do not modify by hand.
 */
package com.tns;

@com.tns.JavaScriptImplementation(javaScriptFile = "./vendor.mjs")
public class OnBackPressedCallback extends androidx.activity.OnBackPressedCallback
    implements com.tns.NativeScriptHashCodeProvider {
  public OnBackPressedCallback(boolean param_0) {
    super(param_0);
    com.tns.Runtime.initInstance(this);
  }

  public void handleOnBackPressed() {
    java.lang.Object[] args = new java.lang.Object[0];
    com.tns.Runtime.callJSMethod(this, "handleOnBackPressed", void.class, args);
  }

  public int hashCode__super() {
    return super.hashCode();
  }

  public boolean equals__super(java.lang.Object other) {
    return super.equals(other);
  }
}
